language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: "d64ef31ce454d3f0821d6b21975acfbb07cf09aab5b0a2572575538abe791507"
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: CGMOH3dUfkFu1pPtJX47iC75SjOo4x7LIiWZVLxM3eIxNysLAYMl9FXXOqlhz4T2voefZ3Zo2TXLZbuT5V7OknzoZeH8U+uWfwQoz21L9LKHA0UeWA7eoWaCqW+sZNgFIqAFGqZFLD3O7j6Gvr7q8UFzeloTX3k6tW43fcxFivfrlMCa3Akwgyl/nZcgWrflHufthCW6bW6oWHeMHXBmRIQT2FgXjf5V5Kv5ZluALAZ13E1yIruYWbqr/ppt+NyHNEJR9zxNctdfKkJsFQEggvsSwL6dENMwNtLhM1nuv/U38FEb3AeoFwIUe8m6npf+BDkzCbihIWvVgvaIR6xfhAKF4gUgc6X1zedjPCJb/Ph3owt8mY80v+HqAAShoMiHk68Yxrb87sJbyyFXQvpTecUcItNqpnPZBYBOp09IjsEeBIBVmBnQE+gdqzoZbai/rzqUPyNsBfjNqlYWmCd7IXP1ck5iNFll2Udxt0mw1z59sk80R+zCpGJEgUq4s4nW++nc3bHACz/KE031C5fsQG/IQLJyVuOiAtughQF+GoGDTjDVDFhUnGStTbtR29ABw2ywff4aB+o1deuts513cxzaKkUC0AL6oH/GxUHwsnVFEGMyz1AyZeQEz3G/TLH9zdIg56VxHf1cZXwh1CUtqdHv6hXVZme0HfY3Sko9/4s=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
